# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".git-rewrite",
	".github",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
	"__pycache__",
    "build",
    "dist",
]

# Same as Black.
line-length = 88
indent-width = 4

target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E", "F", "I", "UP", "W", "B", "SIM"]
# Suppressed PEP8 Codes:
# ignore D203 -> Allow newline after class definition
# ignore F403 -> Allow import * from constants file
# ignore F405 -> Allow import* from constants file
ignore = ["D203", "F403", "F405"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []


dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

